tasks:
- ssh-keys: null
- ceph-ansible: null
- rgw-system-test:
    test-name: test_acls_all_usrs
    config:
       bucket_count: 500
       user_count: 100
       objects_count: 90
       min_file_size: 1000
       max_file_size: 1500