tasks:
- ssh-keys: null
- ceph-ansible: null
- rgw-system-test:
    test-name: test_Mbuckets_with_Nobjects_shards
    config:
      shards: 100
      max_objects: 100000   # max objects per bucket.
      user_count: 100
      bucket_count: 500
      objects_count: 100
      min_file_size: 1000
      max_file_size: 1500