overrides:
  ceph-deploy:
    conf:
      global:
        ms inject delay max: 1
        ms inject delay probability: 0.005
        ms inject delay type: osd
        ms inject internal delays: 0.002
        ms inject socket failures: 2500
        osd pool default size: 2
        osd pool default pg num:  128
        osd pool default pgp num:  128
tasks:
- ssh-keys:
- ceph-deploy:
    fs: xfs
    log-whitelist:
    - wrongly marked me down
    - objects unfound and apparently lost
- thrashosds:
    chance_pgnum_grow: 2
    chance_pgpnum_fix: 1
    timeout: 1200
- full_sequential:
  - radosbench:
      clients: [client.0]
      time: 150
  - radosbench:
      clients: [client.0]
      time: 150
  - radosbench:
      clients: [client.0]
      time: 150
  - radosbench:
      clients: [client.0]
      time: 150
  - radosbench:
      clients: [client.0]
      time: 150
