overrides:
  ceph-deploy:
    conf:
      global:
        osd pool default size: 2
        osd pool default pg num:  128
        osd pool default pgp num:  128
tasks:
- ssh-keys:
- ceph-deploy:
    fs: xfs
- workunit:
    clients:
      client.0:
        - cls
