overrides:
  ceph-deploy:
    conf:
      global:
        osd pool default size: 2
        osd pool default pg num:  128
        osd pool default pgp num:  128
tasks:
-ssh-keys:
-ceph-deploy:
    fs: ext4
    log-whitelist:
    - reached quota
    - wrongly marked me down
    - objects unfound and apparently lost
- thrashosds:
    chance_pgnum_grow: 2
    chance_pgpnum_fix: 1
    timeout: 1200
- workunit:
    clients:
      client.0:
      - rados/test.sh
