overrides:
  ceph:
    conf:
      client:
        rbd cache: false
      global:
        ms inject socket failures: 5000
tasks:
- install: null
- ceph:
    fs: xfs
- thrashosds:
    timeout: 1200
- rbd_fsx:
    clients:
    - client.0
    ops: 2000
